name = "durable-limiter"

compatibility_date = "2022-10-05"
compatibility_flags = ["durable_object_alarms"]

[durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]

[build]
command = "node build.js"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[miniflare]
kv_persist = "./kv-data/"
cache_persist = "./cache-data/"
durable_objects_persist = "./do-data/"
