name = "durable-limiter"
main = "dist/index.mjs"
compatibility_date = "2022-05-28"
compatibility_flags = []

[durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]

[build]
command = "node build.js"

[miniflare]
kv_persist = "./kv-data/"
cache_persist = "./cache-data/"
durable_objects_persist = "./do-data/"
